CREATE TABLE status (
    name TEXT PRIMARY KEY,
    position INTEGER NOT NULL
);

CREATE TABLE recipe (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    hash TEXT NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE meal (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    recipe_uid TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE grocery_item (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE aisle (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE menu (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE photo (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE meal_type (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE pantry_item (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE grocery_ingredient (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE grocery_list (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE bookmark (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE menu_item (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE category (
    id SERIAL PRIMARY KEY,
    uid TEXT UNIQUE NOT NULL,
    data JSONB NOT NULL
);
