CREATE TABLE recipe_category (
    recipe_uid TEXT NOT NULL REFERENCES recipe (uid) ON DELETE CASCADE ON UPDATE CASCADE INITIALLY IMMEDIATE,
    category_uid TEXT NOT NULL REFERENCES category (uid) ON DELETE CASCADE ON UPDATE CASCADE INITIALLY IMMEDIATE,

    PRIMARY KEY (recipe_uid, category_uid)
);
